compare_prices_project/compare_prices_app/urls.py
from django.urls import path
from .views import HomeView


app_name = 'cprice'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
]

compare_prices_project/compare_prices_project/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cprice/', include('compare_prices_app.urls')),
]

compare_prices_project/compare_prices_app/models.py
from django.db import models

# Create your models here.

compare_prices_project/compare_prices_app/forms.py
from dataclasses import field
from django import forms


class CompareForm(forms.Form):
    name = forms.CharField(
        label='検索',
        max_length=50,
    )

compare_prices_project/compare_prices_app/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from time import sleep

from .forms import CompareForm


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_keyword(self):
        keyword = self.request.GET.get('keyword')
        return keyword

    @property
    def amazon_scraping(self):
        options = Options()
        options.add_argument('--headless')
        keyword = self.get_keyword()
        browser = webdriver.Chrome(options=options, executable_path='/Users/shinodashogo/Documents/Python'
                                                                    '/chromedriver/chromedriver')
        amazon_url = 'https://www.amazon.co.jp/'
        browser.get(amazon_url)
        sleep(1)
        elem_search = browser.find_element_by_xpath('//*[@id="twotabsearchtextbox"]')
        elem_search.send_keys(keyword)
        elem_click = browser.find_element_by_xpath('//*[@id="nav-search-submit-button"]')
        elem_click.click()
        sleep(1)
        amazon_products = [[], [], []]
        elems_product_name = browser.find_elements_by_class_name('a-size-base-plus.a-color-base.a-text-normal')
        elems_product_price = browser.find_elements_by_class_name('a-price-whole')
        elems_product_url = browser.find_elements_by_class_name('a-link-normal.s-underline-text.s-underline-link'
                                                                '-text.s-link-style.a-text-normal')
        len_elem = len(elems_product_name)
        if len_elem >= 10:
            loop_num = 10
        else:
            loop_num = len_elem
        for i in range(loop_num):
            amazon_products[0].append(elems_product_name[i].text)
            amazon_products[1].append(elems_product_price[i].text)
            amazon_products[2].append(elems_product_url[i].get_attribute('href'))
        browser.quit()
        return amazon_products

    def rakuten_scraping(self):
        options = Options()
        options.add_argument('--headless')
        keyword = self.get_keyword()
        browser = webdriver.Chrome(options=options, executable_path='/Users/shinodashogo/Documents/Python'
                                                                    '/chromedriver/chromedriver')
        rakuten_url = 'https://www.rakuten.co.jp/'
        browser.get(rakuten_url)
        sleep(1)
        elem_search = browser.find_element_by_xpath('//*[@id="common-header-search-input"]')
        elem_search.send_keys(keyword)
        elem_click = browser.find_element_by_xpath('//*[@id="wrapper"]/div[5]/div/div/div/div['
                                                   '1]/div/div/div/a/div/div/div')
        elem_click.click()
        sleep(1)
        rakuten_products = [[], [], []]
        elems_product_price = browser.find_elements_by_class_name('important')
        elems_product_name = browser.find_elements_by_css_selector('div.content div.title h2')
        elems_product_url = browser.find_elements_by_css_selector('div.content div.title a')
        len_elem = len(elems_product_name)
        if len_elem >= 10:
            loop_num = 10
        else:
            loop_num = len_elem
        for i in range(loop_num):
            rakuten_products[0].append(elems_product_name[i].text)
            rakuten_products[1].append(elems_product_price[i].text)
            rakuten_products[2].append(elems_product_url[i].get_attribute('href'))
        browser.quit()
        return rakuten_products

    def yahoo_scraping(self):
        options = Options()
        options.add_argument('--headless')
        keyword = self.get_keyword()
        browser = webdriver.Chrome(options=options, executable_path='/Users/shinodashogo/Documents/Python'
                                                                    '/chromedriver/chromedriver')
        yahoo_url = 'https://shopping.yahoo.co.jp/'
        browser.get(yahoo_url)
        sleep(1)
        elem_search = browser.find_element_by_xpath('//*[@id="ss_yschsp"]')
        elem_search.send_keys(keyword)
        elem_click = browser.find_element_by_xpath('//*[@id="ss_srch_btn"]')
        elem_click.click()
        sleep(1)
        yahoo_products = [[], [], []]
        elems_product_price = browser.find_elements_by_class_name('_3-CgJZLU91dR')
        elems_product_name = browser.find_elements_by_class_name('_2EW-04-9Eayr')
        elems_product_url = browser.find_elements_by_css_selector('a._2EW-04-9Eayr')
        len_elem = len(elems_product_name)
        if len_elem >= 10:
            loop_num = 10
        else:
            loop_num = len_elem
        for i in range(loop_num):
            yahoo_products[0].append(elems_product_name[i].text)
            yahoo_products[1].append(elems_product_price[i].text)
            yahoo_products[2].append(elems_product_url[i].get_attribute('href'))
        browser.quit()
        return yahoo_products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        keyword = self.get_keyword()
        if keyword:
            amazon_products = self.amazon_scraping
            rakuten_products = self.rakuten_scraping()
            yahoo_products = self.yahoo_scraping()
            context['amazon_products'] = amazon_products
            context['rakuten_products'] = rakuten_products
            context['yahoo_products'] = yahoo_products
        context['keyword'] = keyword
        return context

compare_prices_project/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="GET" action="{% url 'cprice:home' %}">
  <div class="search-wrapper">
    <input type="text" name="keyword">
    <button type="submit">検索</button>
  </div>
</form>
{% if keyword %}
    {{ keyword }}
    <table border="1">
      <tr>
          <th>アマゾン</th>
          <th>楽天</th>
          <th>ヤフー</th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.0 }}">{{ amazon_products.0.0 }}</a></p>
              <p>{{ amazon_products.1.0 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.0 }}">{{ rakuten_products.0.0 }}</a></p>
              <p>{{ rakuten_products.1.0 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.0 }}">{{ yahoo_products.0.0 }}</a></p>
              <p>{{ yahoo_products.1.0 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.1 }}">{{ amazon_products.0.1 }}</a></p>
              <p>{{ amazon_products.1.1 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.1 }}">{{ rakuten_products.0.1 }}</a></p>
              <p>{{ rakuten_products.1.1 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.1 }}">{{ yahoo_products.0.1 }}</a></p>
              <p>{{ yahoo_products.1.1 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.2 }}">{{ amazon_products.0.2 }}</a></p>
              <p>{{ amazon_products.1.2 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.2 }}">{{ rakuten_products.0.2 }}</a></p>
              <p>{{ rakuten_products.1.2 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.2 }}">{{ yahoo_products.0.2 }}</a></p>
              <p>{{ yahoo_products.1.2 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.3 }}">{{ amazon_products.0.3 }}</a></p>
              <p>{{ amazon_products.1.3 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.3 }}">{{ rakuten_products.0.3 }}</a></p>
              <p>{{ rakuten_products.1.3 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.3 }}">{{ yahoo_products.0.3 }}</a></p>
              <p>{{ yahoo_products.1.3 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.4 }}">{{ amazon_products.0.4 }}</a></p>
              <p>{{ amazon_products.1.4 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.4 }}">{{ rakuten_products.0.4 }}</a></p>
              <p>{{ rakuten_products.1.4 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.4 }}">{{ yahoo_products.0.4 }}</a></p>
              <p>{{ yahoo_products.1.4 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.5 }}">{{ amazon_products.0.5 }}</a></p>
              <p>{{ amazon_products.1.5 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.5 }}">{{ rakuten_products.0.5 }}</a></p>
              <p>{{ rakuten_products.1.5 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.5 }}">{{ yahoo_products.0.5 }}</a></p>
              <p>{{ yahoo_products.1.5 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.6 }}">{{ amazon_products.0.6 }}</a></p>
              <p>{{ amazon_products.1.6 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.6 }}">{{ rakuten_products.0.6 }}</a></p>
              <p>{{ rakuten_products.1.6 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.6 }}">{{ yahoo_products.0.6 }}</a></p>
              <p>{{ yahoo_products.1.6 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.7 }}">{{ amazon_products.0.7 }}</a></p>
              <p>{{ amazon_products.1.7 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.7 }}">{{ rakuten_products.0.7 }}</a></p>
              <p>{{ rakuten_products.1.7 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.7 }}">{{ yahoo_products.0.7 }}</a></p>
              <p>{{ yahoo_products.1.7 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.8 }}">{{ amazon_products.0.8 }}</a></p>
              <p>{{ amazon_products.1.8 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.8 }}">{{ rakuten_products.0.8 }}</a></p>
              <p>{{ rakuten_products.1.8 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.8 }}">{{ yahoo_products.0.8 }}</a></p>
              <p>{{ yahoo_products.1.8 }}</p>
          </th>
      </tr>
      <tr>
          <th><p><a href="{{ amazon_products.2.9 }}">{{ amazon_products.0.9 }}</a></p>
              <p>{{ amazon_products.1.9 }}</p>
          </th>
          <th><p><a href="{{ rakuten_products.2.9 }}">{{ rakuten_products.0.9 }}</a></p>
              <p>{{ rakuten_products.1.9 }}</p>
          </th>
          <th>
              <p><a href="{{ yahoo_products.2.9 }}">{{ yahoo_products.0.9 }}</a></p>
              <p>{{ yahoo_products.1.9 }}</p>
          </th>
      </tr>
    </table>
{% endif %}

</body>
</html>